### PR TITLE
grammar pr

### PR DESCRIPTION
**Pull request by Airbus-A330**

### CODE REVIEW

**Comment by Airbus-A330** [comment]
This is a highly important pull request as it relates to grammar - the most essential language mechanic.

**Comment by sinjs** [comment]
Bro what the actual ufkc

**Comment by aeroplaneticdos** [comment]
what the actual fuck

**Comment by Airbus-A330** [comment]
I respectfully disagree with the closure of this essential Pull Request. Correct English grammar is essential to proficient demonstration of the language. Using correct grammar mechanics allows you to accurately convey your message in a way that cannot be misunderstood by others. Please consider re-opening this Pull Request and reviewing it further. Thank you for your time.

**Pull request closed without merging**
